package com.altisource.bugtracker.ha.domain;

// Generated Jan 25, 2015 2:41:43 PM by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Component generated by hbm2java
 */
@Entity
@Table(name = "COMPONENT")
public class Component implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "ID")
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Long compId;

	@Column(name = "NAME", length = 45)
	private String name;

	@Column(name = "DESCRIPTION", length = 1000)
	private String description;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "component")
	private Set<Bug> bugs = new HashSet<Bug>(0);

	public Component() {}

	public Component(String name, String description, Set<Bug> bugs) {
		this.name = name;
		this.description = description;
		this.bugs = bugs;
	}

	public Long getCompId() {
		return this.compId;
	}

	public void setCompId(Long compId) {
		this.compId = compId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<Bug> getBugs() {
		return this.bugs;
	}

	public void setBugs(Set<Bug> bugs) {
		this.bugs = bugs;
	}

}
