package com.altisource.bugtracker.ha.domain;

// Generated Jan 25, 2015 2:41:43 PM by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Project generated by hbm2java
 */
@Entity
@Table(name = "PROJECT", uniqueConstraints = @UniqueConstraint(columnNames = "project_name"))
public class Project implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "ID")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long projectId;

	@Column(name = "PROJECT_NAME", unique = true, length = 45)
	private String projectName;

	@Column(name = "LEAD")
	private Integer lead;

	@Column(name = "NAME")
	private String name;

	@Column(name = "DESCRIPTION")
	private String description;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "project", cascade = CascadeType.ALL)
	private Set<Bug> bugs = new HashSet<Bug>(0);

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "project")
	private Set<User> users = new HashSet<User>(0);

	public Project() {}

	public Project(String projectName, Integer lead, String name,
			String description, Set<Bug> bugs, Set<User> users) {
		this.projectName = projectName;
		this.lead = lead;
		this.name = name;
		this.description = description;
		this.bugs = bugs;
		this.users = users;
	}

	public Long getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Long projectId) {
		this.projectId = projectId;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	public Integer getLead() {
		return this.lead;
	}

	public void setLead(Integer lead) {
		this.lead = lead;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<Bug> getBugs() {
		return this.bugs;
	}

	public void setBugs(Set<Bug> bugs) {
		this.bugs = bugs;
	}

	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

}
