package com.altisource.bugtracker.ha.domain;

// Generated Jan 25, 2015 2:41:43 PM by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Version generated by hbm2java
 */
@Entity
@Table(name = "VERSION")
public class Version implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "ID")
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Long versionId;

	@Column(name = "NAME", length = 45)
	private String name;

	@Column(name = "DESCRIPTION", length = 1000)
	private String description;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "versionByFixedVersion")
	private Set<Bug> bugsForFixedVersion = new HashSet<Bug>(0);

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "versionByAffectedVersion")
	private Set<Bug> bugsForAffectedVersion = new HashSet<Bug>(0);

	public Version() {}

	public Version(String name, String description,
			Set<Bug> bugsForFixedVersion, Set<Bug> bugsForAffectedVersion) {
		this.name = name;
		this.description = description;
		this.bugsForFixedVersion = bugsForFixedVersion;
		this.bugsForAffectedVersion = bugsForAffectedVersion;
	}

	public Long getVersionId() {
		return this.versionId;
	}

	public void setVersionId(Long versionId) {
		this.versionId = versionId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<Bug> getBugsForFixedVersion() {
		return this.bugsForFixedVersion;
	}

	public void setBugsForFixedVersion(Set<Bug> bugsForFixedVersion) {
		this.bugsForFixedVersion = bugsForFixedVersion;
	}

	public Set<Bug> getBugsForAffectedVersion() {
		return this.bugsForAffectedVersion;
	}

	public void setBugsForAffectedVersion(Set<Bug> bugsForAffectedVersion) {
		this.bugsForAffectedVersion = bugsForAffectedVersion;
	}

}
